version: '2'
services:
  nginx:
    image: jancyril/nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
    - /home/jancyril/Code/jcms:/var/www/html
    networks:
    - appnet
  php:
    image: jancyril/php:7.1
    volumes:
    - /home/jancyril/Code/jcms:/var/www/html
    networks:
    - appnet
  redis:
    image: redis:alpine
    networks:
    - appnet
  supervisor:
    image: jancyril/supervisor
    volumes:
    - /home/jancyril/Code/jcms:/app
    networks:
    - appnet
  node:
    image: jancyril/node:stable-alpine
    volumes:
    - /home/jancyril/Code/jcms:/var/www/html
    networks:
    - appnet
    tty: true
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: jcms
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
    - data:/var/lib/mysql
    networks:
    - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
    - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
