version: '2'
services:
  nginx:
    image: jancyril/nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  php:
    image: jancyril/php:7.1
    volumes:
     - ./application:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - data:/var/lib/mysql
    networks:
     - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
    - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
